# Create transactions

POST http://localhost:8080/v1/stocks/transaction
Content-Type: application/json

{
  "userId": "user",
  "ticker": "APPL",
  "date" : "2023-12-25T18:36:24.00Z",
  "quantity": 5,
  "price": 200.0,
  "transactionType": "SELL",
  "currency": "USD"
}

### Get all transactions

GET http://localhost:8080/v1/stocks/transactions?userId=user&currency=USD&page=1
Content-Type: application/json

